# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinderToolsetHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinderToolsetHelper

end

target 'FinderToolset' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 修改为可继承类
  pod 'Preferences', :git => 'https://github.com/liyb93/Preferences.git'
  # Pods for FinderToolset

end

target 'FinderToolsetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinderToolsetExtension

end
