# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aToolsetHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aToolsetHelper

end

target 'Toolset' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 修改为可继承类
  pod 'Preferences', :git => 'https://github.com/liyb93/Preferences.git'
  # Pods for Toolset

end

target 'ToolsetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToolsetExtension

end
